# Changes here will be overwritten by Copier.
_commit: 1.12.1
_src_path: gh:pawamoy/copier-uv
author_email: 47255277+deadhand777@users.noreply.github.com
author_fullname: deadhand777
author_username: deadhand777
copyright_date: '2026'
copyright_holder: deadhand777
copyright_holder_email: 47255277+deadhand777@users.noreply.github.com
copyright_license: MIT
project_description: SVOD (Subscription Video on Demand) subscribers in the USA
project_name: svod
python_package_command_line_name: svod
python_package_distribution_name: svod
python_package_import_name: svod
repository_name: svod
repository_namespace: deadhand777
repository_provider: github.com

