[pytest]
python_files =
  test_*.py
addopts =
  --cov
  --cov-config config/coverage.ini
testpaths =
  tests

# action:message_regex:warning_class:module_regex:line
filterwarnings =
  error
  default::EncodingWarning
  error::EncodingWarning:svod
  # TODO: remove once pytest-xdist 4 is released
  ignore:.*rsyncdir:DeprecationWarning:xdist
  ignore::DeprecationWarning:sklearn
  ignore::FutureWarning:sklearn
  ignore::DeprecationWarning:shap
  ignore::UserWarning:shap
  ignore::DeprecationWarning:numba
  ignore::DeprecationWarning:plotly
  ignore::DeprecationWarning:pandas
  ignore::UserWarning:openpyxl
